In [72]:
import pandas as pd

ruta_dex = "Austin-Johns-SHINY-Pokemon-Home-Organizer-1.4-PLZA - Dex.csv"
ruta_imp_idx = "Austin-Johns-SHINY-Pokemon-Home-Organizer-1.4-PLZA - Imported Index.csv"

df_dex = pd.read_csv(ruta_dex)
df_imp_idx = pd.read_csv(ruta_imp_idx)

df_imp_idx_2 = df_imp_idx[~df_imp_idx['S-LivingForm'].str.contains('gen', case=False, na=False)].reset_index(drop=True)

df_dex_c = df_dex.copy()
df_imp_idx_c = df_imp_idx_2.copy()[['S-LivingForm', 'Unnamed: 1']]

df_dex_c['id_home'] = df_dex_c.index + 1
df_imp_idx_c['id_home'] = df_imp_idx_c.index + 1

In [73]:
df_dex_c = df_dex_c.set_index('id_home')
df_imp_idx_c = df_imp_idx_c.set_index('id_home')

In [53]:
print(df_dex_c['Keyword'].tail(10))

df_dex_c = df_dex_c.iloc[:1387]

df_dex_c.tail(3)

id_home
1386    Terapagos
1387    Pecharunt
1388          Gen
1389          Gen
1390          Gen
1391          Gen
1392          Gen
1393          Gen
1394          Gen
1395          Gen
Name: Keyword, dtype: object

,Keyword,Form name,-Form,-Gender,FormDex,Keyword.1,Nat,SwSh,BDSP,PLA,SV,PLZA
id_home,,,,,,,,,,,,
1385,Iron Crown,NaN,NaN,NaN,1023,iron crown,1023.0,NaN,NaN,NaN,B238,NaN
1386,Terapagos,NaN,NaN,NaN,1024,terapagos,1024.0,NaN,NaN,NaN,B240,NaN
1387,Pecharunt,NaN,NaN,NaN,1025,pecharunt,1025.0,NaN,NaN,NaN,NaN,NaN

In [75]:
df_imp_idx_c.tail(3)

        S-LivingForm  Unnamed: 1
id_home
1311      iron crown         1.0
1312       terapagos         1.0
1313       pecharunt         1.0

In [78]:
# Suponiendo que tus DataFrames se llaman df_dex y df_imported

# Pasamos los nombres a un 'set' (conjunto matemático)
pokemon_en_dex = set(df_dex_c['Keyword.1'])
pokemon_en_imported = set(df_imp_idx_c['S-LivingForm'])

# 1. ¿Qué hay en DEX que falta en IMPORTED INDEX?
print("Faltan en Imported Index:", pokemon_en_dex - pokemon_en_imported)

# 2. ¿Qué hay en IMPORTED INDEX que no existe en DEX?
print("Faltan en Dex:", pokemon_en_imported - pokemon_en_dex)

Faltan en Imported Index: {'alcremie-1-f', 'floette-5', 'pikachu-3', 'alcremie-4-a', 'alcremie-7-a', 'pikachu-2', 'alcremie-5-c', 'alcremie-8-e', 'alcremie-7-d', 'pikachu-5', 'alcremie-5-a', 'pikachu-1', 'gengar', 'alcremie-6-d', 'alcremie-5-f', 'hoopa-1', 'minior-5', 'minior-2', 'minior-6', 'alcremie-5-b', 'alcremie-8-a', 'alcremie-3-e', 'alcremie-1-d', 'alcremie-3-d', 'alcremie-2-d', 'alcremie-7-c', 'roggenrola', 'alcremie-4-e', 'alcremie-3-f', 'alcremie-5-e', 'gen', 'alcremie-4-b', 'alcremie-5-d', 'alcremie-e', 'alcremie-a', 'alcremie-3-a', 'alcremie-3-c', 'alcremie-3-b', 'alcremie-1-c', 'alcremie-1-e', 'alcremie-4-d', 'alcremie-6-b', 'alcremie-d', 'alcremie-4-c', 'alcremie-4-f', 'alcremie-1-b', 'alcremie-2-a', 'alcremie-6-a', 'alcremie-2-e', 'alcremie-2-c', 'alcremie-8', 'genesect', 'alcremie-b', 'alcremie-2-f', 'minior-1', 'alcremie-7', 'pikachu-6', 'alcremie-6-e', 'minior-4', 'alcremie-1-a', 'alcremie-7-f', 'alcremie-c', 'pikachu-9', 'alcremie-8-c', 'alcremie-8-d', 'alcremie-7-e', 'alcremie-f', 'alcremie-6-c', 'alcremie-8-f', 'alcremie-6-f', 'alcremie-8-b', 'alcremie-7-b', 'alcremie-2-b', 'pikachu-4', 'minior-3', 'pikachu-7'}
Faltan en Dex: set()